### ISSUE TITLE
LammpsData object cannot be instantiated with pandas version 1.0.1

### ISSUE THREAD

**Issue by Bernardo-A-Roque** [compMathUPRH/granules#4]
running interactively on python3 version GCC 8.3.0 on ubuntu linux, and pandas version 1.0.1 throws the following error (I have replaced my username with the word 'user' ) :

>>> from granules.structure.LAMMPSdata import LammpsData
>>> l = LammpsData()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/granules/structure/LAMMPSdata.py", line 755, in __init__
    self.atoms       = AtomsDF()
  File "/home/user/.local/lib/python3.6/site-packages/granules/structure/LAMMPSdata.py", line 132, in __init__
    super(AtomsDF, self).__init__(self.drop([0]))
  File "/home/user/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3997, in drop
    errors=errors,
  File "/home/user/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3936, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/user/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3971, in _drop_axis
    result = self.reindex(**{axis_name: new_axis})
  File "/home/user/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3856, in reindex
    return self._ensure_type(super().reindex(**kwargs))
  File "/home/user/.local/lib/python3.6/site-packages/pandas/core/base.py", line 93, in _ensure_type
    assert isinstance(obj, type(self)), type(obj)
AssertionError: <class 'pandas.core.frame.DataFrame'>

for the time being, I downgraded my pandas version

**Comment by Bernardo-A-Roque** [comment]
works with pandas 1.03, was probably a problem with that specific pandas version
